version: 0.2

phases:
  install:
    commands:
      - echo Install root dependencies...
      - yarn install # If there are any root dependencies to install

  pre_build:
    commands:
      - echo Making detect_changes.sh executable...
      - chmod +x detect_changes.sh
      - echo Checking for changes in the packages...
      - echo "Changed packages:" $(./detect_changes.sh)

  build:
    commands:
      - echo Building and analyzing changed packages...
      - |
        for PROJECT in $CHANGED_PROJECTS; do
          cd packages/$PROJECT
          if [[ "$PROJECT" == "microservice-A" ]]; then
            echo "Running Maven build and SonarQube analysis for Microservice-A"
            mvn clean install
            mvn sonar:sonar -Dsonar.host.url=[SonarQube_URL] -Dsonar.login=[SonarQube_Token]
          elif [[ "$PROJECT" == "microservice-B" ]]; then
            echo "Running Gradle build and SonarQube analysis for Microservice-B"
            ./gradlew build
            ./gradlew sonarqube -Dsonar.host.url=[SonarQube_URL] -Dsonar.login=[SonarQube_Token]
          elif [[ "$PROJECT" == "microservice-C" ]]; then
            echo "Running Yarn build and SonarQube analysis for Microservice-C"
            yarn install
            yarn run build
            sonar-scanner -Dsonar.projectKey=[MicroserviceC_ProjectKey] -Dsonar.host.url=[SonarQube_URL] -Dsonar.login=[SonarQube_Token]
          fi
          cd - # This takes you back to the previous directory (one level up)
        done

  post_build:
    commands:
      - echo Build and analysis completed for changed packages.

# Make sure to replace the placeholder values with your actual SonarQube URL, tokens, and project keys.
