version: 0.2

phases:
  install:
    commands:
      # Add commands to install dependencies for all projects if needed
      - echo Install root dependencies...
      - yarn install

  pre_build:
    commands:
      - echo Making detect_changes.sh executable...
      - chmod +x detect_changes.sh
      - echo Checking for changes in the packages...
      - CHANGED_PROJECTS=$(./detect_changes.sh)
      - echo Changed packages: $CHANGED_PROJECTS

  build:
    commands:
      - echo Building and analyzing changed packages...
      - |
        for PROJECT in $CHANGED_PROJECTS; do
          cd packages/$PROJECT
          if [[ "$PROJECT" == "simple-express-server" ]]; then
            echo "SONARQUBE FOR SIMPLE-EXPRESS-SERVER"
          elif [[ "$PROJECT" == "simple-react-app" ]]; then
            echo "SONARQUBE FOR SIMPLE-REACT-APP"
          elif [[ "$PROJECT" == "simple-shared-data" ]]; then
            echo "SONARQUBE FOR SIMPLE-SHARED-DATA"
          fi
          cd ../..
        done

  post_build:
    commands:
      - echo Build and analysis completed for changed packages.

# Make sure to replace the placeholder values with your actual SonarQube URL, tokens, and project keys.
